# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  server:
    image: badea741/soccerapi
    build:
      context: .
      dockerfile: Soccer.Api/Dockerfile
    ports:
      - 5000:5000
    command: ["dotnet", "ef","--startup-project=../Soccer.Api/Soccer.Api.csproj", "database update"]
    depends_on:
      - db

  db:
     image: mysql/mysql-server:latest
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: SoccerDb
       MYSQL_USER: root
       MYSQL_PASSWORD: 2510203121
     volumes:
       - dbdata2:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always
volumes:
    dbdata2: