# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  server:
    image: soccerapi:build
    build:
      context: .
      dockerfile: Soccer.Api/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - server-database
    volumes:
      - .:/src

  db:
     image: mysql/mysql-server:latest
     environment:
       MYSQL_ROOT_PASSWORD: 2510203121
       MYSQL_DATABASE: SoccerDb
      #  MYSQL_USER: root
       MYSQL_PASSWORD: 2510203121
       
     volumes:
       - dbvolum1:/var/lib/mysql
     networks:
       - server-database
     restart: always
volumes:
    dbvolum1:
networks:
  server-database:
    driver: bridge